### ISSUE TITLE
Minimist missing as a dependency

### ISSUE THREAD

**Issue by moll** [w8r/geojson2svg#11]
Hey,

I believe the `minimist` module is missing from actual dependencies (as opposed to `devDependencies`) as the executable variant of geojson2svg depends on it. Given the executable is installed along with geojson2svg itself, and not hidden in a `./scripts` directoy, for example, I'd say `minimist` is therefore a production dependency.

Cheers

**Comment by w8r** [comment]
Fixed, cheers
