### ISSUE TITLE
may be of interest to you

### ISSUE THREAD

**Issue by gagan-bansal** [w8r/geojson2svg#2]
Quite interesting project as you are developing for command line also.

Here is the similar work I did [geojson2svg](https://www.npmjs.com/package/geojson2svg), may be of interest to you.

**Comment by w8r** [comment]
@gagan-bansal thanks a lot! I saw your project, it's a good one!
I am aiming here to produce something that would be able to do the following:

 * work with non-cartographical data (geometries and schematics), with an option to apply arbitrary projection
 * work with comprehensible styling, including path decorators, svg markers, ans svg symbols
 * would be able to work on Node with required font data

**Comment by w8r** [comment]
@gagan-bansal by styling I mean something Leaflet-compitable that would allow you to provide styling in a separate file but also on top of it in feature properties.

**Comment by gagan-bansal** [comment]
Yes most interesting feature I see in your project is converting geojson to SVG at back-end itself with  style. So that now the output SVG can be used easily as Image or with minimal programming by front end developer.

**Comment by w8r** [comment]
Exactly, and at a great speed, cause it's plain text renderer, which can also be quite useful on the client-side

also I didn't want to use `d3` for simple `SVG` rendering, 
```
d3 !== SVG
```

**Comment by gagan-bansal** [comment]
Wish you all the best for this project.
Gagan
